#!/bin/bash

# Define source and destination paths
SOURCE_PATH="$HOME/Shared"
DEST_PATH="samodra.me:Shared"

# Function to display usage instructions
usage() {
    echo "Usage: drive [pull|push]"
    exit 1
}

# Function to confirm action
confirm_action() {
    local action=$1
    read -p "Are you sure you want to $action? This may overwrite files. (y/N): " confirmation
    if [[ "$confirmation" != "y" && "$confirmation" != "Y" ]]; then
        echo "Operation canceled."
        exit 1
    fi
}

# Main script logic
case "$1" in
    pull)
        confirm_action "overwrite local files with remote files"
        rclone sync "$DEST_PATH" "$SOURCE_PATH"
        ;;
    push)
        confirm_action "overwrite remote files with local files"
        rclone sync "$SOURCE_PATH" "$DEST_PATH"
        ;;
    *)
        usage
        ;;
esac
